#!/usr/bin/env python3
"""
Quick setup script to configure Calendly API key
Usage: python setup_env.py
"""

import os
import sys
from pathlib import Path

def main():
    print("🔧 Calendly Analytics - Environment Setup")
    print("=" * 50)
    
    # Get project root
    root_dir = Path(__file__).parent.parent
    backend_dir = root_dir / "backend"
    env_file = backend_dir / ".env"
    
    print(f"\n📁 Backend directory: {backend_dir}")
    print(f"📄 Environment file: {env_file}")
    
    # Check if .env exists
    if env_file.exists():
        print(f"\n✅ .env file already exists")
        
        # Read current content
        with open(env_file, 'r') as f:
            content = f.read()
        
        # Check if API key is set
        if "CALENDLY_API_KEY=" in content:
            for line in content.split('\n'):
                if line.startswith('CALENDLY_API_KEY='):
                    api_key = line.split('=', 1)[1].strip()
                    if api_key and api_key != "your_calendly_api_key_here":
                        print(f"   API Key is set: {api_key[:20]}...")
                        
                        response = input("\n🔄 Do you want to update the API key? (y/n): ")
                        if response.lower() != 'y':
                            print("\n✅ Setup complete! Run: python scripts/run_app.py")
                            return
                    break
    
    # Get API key from user
    print("\n" + "=" * 50)
    print("📋 Get your Calendly API Key:")
    print("   1. Go to: https://calendly.com/integrations/api_webhooks")
    print("   2. Click 'Get a token' or 'Generate New Token'")
    print("   3. Copy the token")
    print("=" * 50)
    
    api_key = input("\n🔑 Enter your Calendly API Key: ").strip()
    
    if not api_key:
        print("\n❌ No API key provided. Exiting.")
        sys.exit(1)
    
    if len(api_key) < 20:
        print("\n⚠️  Warning: API key seems too short. Are you sure it's correct?")
        response = input("   Continue anyway? (y/n): ")
        if response.lower() != 'y':
            sys.exit(1)
    
    # Create .env content
    env_content = f"""# Calendly Analytics Configuration
# Generated by setup_env.py

# CRITICAL: Your Calendly API Key
CALENDLY_API_KEY={api_key}

# Secret key for JWT (change in production)
SECRET_KEY=dev-secret-key-change-in-production-{os.urandom(8).hex()}

# CORS settings
ALLOWED_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000","http://localhost:8000"]

# Data directory (relative to backend folder)
DATA_DIR=../calendly_dump
"""
    
    # Write .env file
    backend_dir.mkdir(parents=True, exist_ok=True)
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Successfully created {env_file}")
    print(f"   API Key: {api_key[:20]}...")
    
    # Create data directory
    data_dir = root_dir / "calendly_dump"
    data_dir.mkdir(parents=True, exist_ok=True)
    print(f"✅ Created data directory: {data_dir}")
    
    print("\n" + "=" * 50)
    print("🎉 Setup Complete!")
    print("=" * 50)
    print("\n📝 Next steps:")
    print("   1. Run: python scripts/run_app.py")
    print("   2. Open: http://localhost:3000")
    print("   3. Click 'Download Calendly Data'")
    print("\n" + "=" * 50)

if __name__ == '__main__':
    main()